/*
  El árbol. Mismo formato que `flor.ts`: rejilla de 16×16, un carácter por píxel.

  Crece a lo alto y a lo ancho: el tronco se engorda y la copa se abre. La
  floreciente añade frutos, que es lo que la separa de la madura de un vistazo.
*/

/** 0 · Semilla. */
export const ARBOL_0 = `
................
................
................
................
................
................
................
................
................
................
................
................
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 1 · Brote: dos hojas sobre un tallo corto. */
export const ARBOL_1 = `
................
................
................
................
................
................
................
................
................
.....gg.gg......
....gggGggg.....
.......G........
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 2 · Joven: tronco fino y copa pequeña. */
export const ARBOL_2 = `
................
................
................
................
................
......gggg......
.....gggggg.....
.....ggGggg.....
......gggg......
.......GG.......
.......GG.......
.......GG.......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 3 · Madura: tronco ancho y copa grande. */
export const ARBOL_3 = `
................
................
.....gggggg.....
....gggggggg....
...gggggGgggg...
...ggGggggggg...
....gggggggg....
.....gggggg.....
......gGGg......
.......GG.......
.......GG.......
......GGGG......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 4 · Floreciente: la copa entera y con frutos. */
export const ARBOL_4 = `
.....gggggg.....
...gggggggggg...
..gggrgggggrgg..
..gggggGgggggg..
..ggrgggggggrg..
..gggggggggggg..
...gggrggggggg..
....gggggggg....
.....ggGGgg.....
.......GG.......
.......GG.......
.......GG.......
......GGGG......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
`;

/** Marchita: el tronco doblado y la copa deshecha. */
export const ARBOL_MARCHITA = `
................
................
................
................
................
................
.........RR.....
........RrR.....
.......RR.......
......GG........
.....GG.........
....GG..........
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

export const ARBOL = [ARBOL_0, ARBOL_1, ARBOL_2, ARBOL_3, ARBOL_4] as const;
