/*
  El cactus. Mismo formato que `flor.ts`.

  Es la especie que con emoji NO crecía: 🌵 repetido cuatro veces. Aquí sube de
  bola a columna, le sale un brazo y acaba con flor. Cinco siluetas distintas,
  que es lo que el jardín prometía.
*/

/** 0 · Semilla. */
export const CACTUS_0 = `
................
................
................
................
................
................
................
................
................
................
................
................
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 1 · Brote: una bola pequeña. */
export const CACTUS_1 = `
................
................
................
................
................
................
................
................
................
......gggg......
.....gGggGg.....
.....gGggGg.....
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 2 · Joven: columna corta. */
export const CACTUS_2 = `
................
................
................
................
................
................
......gggg......
.....gGggGg.....
.....gGggGg.....
.....gGggGg.....
.....gGggGg.....
.....gGggGg.....
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 3 · Madura: columna con un brazo. */
export const CACTUS_3 = `
................
................
................
......gggg......
.....gGggGg.....
..gg.gGggGg.....
.gGg.gGggGg.....
.gGg.gGggGg.....
.gGggGGggGg.....
.gGGGGGggGg.....
.....gGggGg.....
.....gGggGg.....
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 4 · Floreciente: los dos brazos y la flor arriba. */
export const CACTUS_4 = `
......rrrr......
.....rRrrRr.....
......gggg......
.....gGggGg.....
..gg.gGggGg.gg..
.gGg.gGggGg.gGg.
.gGg.gGggGg.gGg.
.gGggGGggGGggGg.
.gGGGGGggGGGGGg.
.....gGggGg.....
.....gGggGg.....
.....gGggGg.....
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** Marchita: la columna vencida y sin firmeza. */
export const CACTUS_MARCHITA = `
................
................
................
................
................
................
................
................
.........RRR....
........RRR.....
.......RRR......
......RR........
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

export const CACTUS = [
  CACTUS_0,
  CACTUS_1,
  CACTUS_2,
  CACTUS_3,
  CACTUS_4,
] as const;
