/*
  Las ocho decoraciones de la tienda, en rejilla como todo lo demás del jardín.

  Ninguna inventa un color: todas usan las letras de `PALETA_PIXEL`, que apuntan
  a tokens que ya existen. Si algún día cambia la paleta del dashboard, cambian
  también los adornos.
*/

export const PIEDRA = `
................
................
................
................
................
................
................
................
......nnnn......
.....nppnnn.....
....nnppnnnn....
...nnnnnnnnnn...
..nnnnnnnnnnnn..
..nNnnnnnnnnNn..
..NNNNNNNNNNNN..
................
`;

export const VALLA = `
........................
..m..........m..........
..m..........m.........m
mmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMMM
..m..........m.........m
mmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMMM
..m..........m.........m
..M..........M.........M
`;

export const FAROL = `
................
.....nnnnnn.....
....nnaaaann....
....naaaaaan....
....naaaaaan....
....naaaaaan....
....nnaaaann....
.....nnnnnn.....
.......nn.......
.......nn.......
.......nn.......
.......nn.......
.......nn.......
......nnnn......
.....nnnnnn.....
................
`;

export const BANCO = `
................
................
..m..........m..
..mmmmmmmmmmmm..
..MMMMMMMMMMMM..
..m..........m..
..mmmmmmmmmmmm..
..MMMMMMMMMMMM..
................
................
..m..........m..
..m..........m..
..m..........m..
..M..........M..
................
................
`;

export const ESTANQUE = `
................
................
................
................
................
.....mmmmmm.....
...mmccccccmm...
..mccccppcccm...
..mccCcccccccm..
..mccccccCccm...
...mmccccccmm...
.....mmmmmm.....
................
................
................
................
`;

export const ESPANTAPAJAROS = `
................
......aaaa......
.....aaaaaa.....
.....aNaaNa.....
.....aaaaaa.....
......aaaa......
..mmmmmmmmmmmm..
..MM..rrrr..MM..
......rrrr......
......rrrr......
......rrrr......
.......mm.......
.......mm.......
.......mm.......
.......MM.......
................
`;

export const GATO = `
................
................
...nn......nn...
...nnn....nnn...
...nnnnnnnnnn...
..nnppnnnnppnn..
..nnnnnnnnnnnn..
..nnnnrrrrnnnn..
...nnnnnnnnnn...
....nnnnnnnn..n.
....nnnnnnnn..n.
....nnnnnnnn.nn.
....nn....nn.nn.
....nn....nn.nn.
....NN....NN....
................
`;

export const ARCOIRIS = `
......rrrrrr......
....rrrrrrrrrr....
...rraaaaaaaarr...
..rraa......aarr..
..raa..gggg..aar..
.raa..gg..gg..aar.
.ra..gg.cc.gg..ar.
.ra..g.cc..g...ar.
.ra..g.c....g..ar.
.ra..g.c....g..ar.
`;
