/*
  La fauna: pájaros para la música, mariposas para las tareas.

  Igual que los adornos, no inventan colores: solo letras de `PALETA_PIXEL`.
*/

export const PAJARO = `
............
............
...nn.......
..nnnn...nn.
.nnaannnnnn.
.nnnnnnnnn..
..nnnnnn....
...nnnn.....
....nn......
............
............
............
`;

export const MARIPOSA = `
............
...n.....n..
..nn.....nn.
.rrrn...nrrr
rrrrrn.nrrrr
rrarrnnnrrar
rrrrrn.nrrrr
.rrrn...nrrr
..rn.....nr.
...n.....n..
............
............
`;
