/*
  La flor, sus cinco etapas y sus dos estados.

  Rejilla de 16×16. Se lee de arriba abajo, así que la tierra está en las últimas
  filas y la planta crece hacia arriba desde ahí.

  Letras: g/G hoja y tallo · r/R pétalos · a centro · m/M tierra · . nada.
  Ver `core/ui/pixel/rejilla.ts` para la paleta entera.

  CADA ETAPA CAMBIA DE SILUETA, no solo de tamaño. Es lo que el jardín prometía
  con emoji y no cumplía: tres de las cinco especies repetían el mismo dibujo.
*/

/** 0 · Semilla: tierra removida, nada asoma todavía. */
export const FLOR_0 = `
................
................
................
................
................
................
................
................
................
................
................
................
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 1 · Brote: dos hojas pequeñas sobre el tallo. */
export const FLOR_1 = `
................
................
................
................
................
................
................
................
.......g........
....gggGggg.....
.....gg.gg......
.......G........
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 2 · Joven: tallo alto y un capullo cerrado. */
export const FLOR_2 = `
................
................
................
................
.......rr.......
......rRRr......
......rRRr......
.......GG.......
.....gggGg......
....gg..G..gg...
........G.......
.......GG.......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 3 · Madura: la flor abierta. */
export const FLOR_3 = `
................
................
......rrrr......
.....rRrrRr.....
....rr.aa.rr....
....rr.aa.rr....
.....rRrrRr.....
......rrrr......
.......GG.......
.....gggGg......
....gg..G..gg...
.......GG.......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 4 · Floreciente: la flor grande y dos capullos a los lados. */
export const FLOR_4 = `
......rrrr......
.....rRrrRr.....
....rrraarrr....
...rr.raar.rr...
...rr.raar.rr...
....rrraarrr....
.....rRrrRr.....
..rr..rrrr..rr..
..rR...GG...Rr..
...g...GG...g...
.....gggGg......
....gg..G..gg...
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/**
 * Marchita: la silueta CAÍDA, no solo apagada.
 *
 * Si se distinguiera únicamente por el color, quien no lo perciba bien vería una
 * flor sana. La forma es la señal; el tono, el refuerzo.
 */
export const FLOR_MARCHITA = `
................
................
................
................
................
................
................
................
.........RRr....
........RrrR....
.......GG.r.....
......GG........
.....GG.........
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
`;

/** Las cinco etapas, en orden. */
export const FLOR = [FLOR_0, FLOR_1, FLOR_2, FLOR_3, FLOR_4] as const;
