/*
  La hierba. Mismo formato que `flor.ts`.

  Crece por acumulación: de tres briznas a una mata, y la floreciente saca
  espigas en ámbar. Es la que menos altura gana, así que su crecimiento se nota
  sobre todo en la anchura de la mata.
*/

/** 0 · Semilla. */
export const HIERBA_0 = `
................
................
................
................
................
................
................
................
................
................
................
................
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 1 · Brote: tres briznas cortas. */
export const HIERBA_1 = `
................
................
................
................
................
................
................
................
................
.....g.g.g......
.....g.g.g......
.....GGGGG......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 2 · Joven: mata baja. */
export const HIERBA_2 = `
................
................
................
................
................
................
................
................
....g.g.g.g.....
....g.g.g.g.....
...gGgGgGgGg....
...gGgGgGgGg....
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 3 · Madura: mata alta y ancha. */
export const HIERBA_3 = `
................
................
................
................
...g.g.g.g.g....
...g.g.g.g.g....
..gGgGgGgGgGg...
..gGgGgGgGgGg...
..gGgGgGgGgGg...
..gGgGgGgGgGg...
.ggGgGgGgGgGgg..
.ggGgGgGgGgGgg..
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 4 · Floreciente: con espigas. */
export const HIERBA_4 = `
...a.a...a.a....
...a.a...a.a....
...A.A...A.A....
..gG.Gg.gG.Gg...
..gG.Gg.gG.Gg...
..gGgGgGgGgGg...
..gGgGgGgGgGg...
..gGgGgGgGgGg...
.ggGgGgGgGgGgg..
.ggGgGgGgGgGgg..
.ggGgGgGgGgGgg..
.ggGgGgGgGgGgg..
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** Marchita: la mata entera vencida hacia dentro, no una sola brizna. */
export const HIERBA_MARCHITA = `
................
................
................
................
................
................
................
................
................
..RR........RR..
...RR......RR...
....RR....RR....
.....RRRRRR.....
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
`;

export const HIERBA = [
  HIERBA_0,
  HIERBA_1,
  HIERBA_2,
  HIERBA_3,
  HIERBA_4,
] as const;
