/*
  El hongo. Mismo formato que `flor.ts`.

  La otra especie que con emoji NO crecía: 🍄 repetido cuatro veces. Aquí sube de
  punto a sombrero, el sombrero se abre, y la floreciente es un corro de tres.

  Es la única que no usa verde: sombrero en coral con lunares de papel, pie en
  papel-2. Así se distingue de las demás incluso de lejos.
*/

/** 0 · Semilla. */
export const HONGO_0 = `
................
................
................
................
................
................
................
................
................
................
................
................
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 1 · Brote: un punto que asoma. */
export const HONGO_1 = `
................
................
................
................
................
................
................
................
................
................
.......rr.......
.......PP.......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 2 · Joven: sombrero pequeño. */
export const HONGO_2 = `
................
................
................
................
................
................
................
................
......rrrr......
.....rrpprr.....
.....rrrrrr.....
......PPPP......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 3 · Madura: sombrero abierto. */
export const HONGO_3 = `
................
................
................
................
................
.....rrrrrr.....
....rrppprrr....
...rrrpprrrrr...
...rrrrrrrrrr...
....RRRRRRRR....
......PPPP......
......PPPP......
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** 4 · Floreciente: un corro de tres. */
export const HONGO_4 = `
................
................
.....rrrrrr.....
....rrppprrr....
...rrrrrrrrrr...
....RRRRRRRR....
......PPPP......
..rrr.PPPP.rrr..
.rrprr....rrprr.
.rrrrr....rrrrr.
..RRR......RRR..
..PPP......PPP..
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
................
`;

/** Marchita: el sombrero caído y el pie doblado. */
export const HONGO_MARCHITA = `
................
................
................
................
................
................
................
................
................
.........RRR....
........RRRR....
.......RR.......
......RR........
....mmMmmMmm....
...mmmmmmmmmm...
..MmmmmmmmmmmM..
`;

export const HONGO = [HONGO_0, HONGO_1, HONGO_2, HONGO_3, HONGO_4] as const;
